SerwisOgloszeniowy/Models/Advert.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SerwisOgloszeniowy.Models
{
    public class Advert
    {
        public int Id { get; set; }
        [Required]
        [DisplayName("Tytuł")]
        public string Title { get; set; }
        [DisplayName("Opis")]
        public string Description { get; set; }
        public string UserID { get; set; }
        [DisplayName("Zdjęcia")]
        public virtual ICollection<ImagePath> ImagePaths { get; set; }
    }
}

SerwisOgloszeniowy/Controllers/AdvertsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SerwisOgloszeniowy.Models;
using Microsoft.AspNet.Identity;
using System.IO;
using PagedList;
using Microsoft.AspNet.Identity.Owin;

namespace SerwisOgloszeniowy.Controllers
{
    public class AdvertsController : Controller
    {
        private OgloszeniaContext db = new OgloszeniaContext();

        
        public ActionResult Index(String sortOrder, AdvertSearch search, int? page)
        {
            int pageSize = 3;
            int pageNumber = (page ?? 1);

            ViewBag.CurrentID = User.Identity.GetUserId();
            ViewBag.IdSortParm = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewBag.TitleSortParm = sortOrder == "title_asc" ? "title_desc" : "title_asc";
            var adverts = db.Adverts.Include(i => i.ImagePaths);
            switch (sortOrder)
            {
                case "title_desc": adverts = adverts.OrderByDescending(s => s.Title); break;
                case "title_asc": adverts = adverts.OrderBy(s => s.Title); break;
                case "id_desc": adverts = adverts.OrderByDescending(s => s.Id); break;
                default: adverts = adverts.OrderBy(s => s.Id); break;
            }
            
            if (search != null)
            {
                if (search.DescriptionSearch == null)
                    search.DescriptionSearch = "";
                if (search.TitleSearch == null)
                    search.TitleSearch = "";
                adverts = adverts.Where(
                        x => x.Title.Contains(search.TitleSearch) && 
                        x.Description.Contains(search.DescriptionSearch)
                        );
            }

            return View(adverts.ToPagedList(pageNumber, pageSize));
        }
        // GET: Adverts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advert advert = db.Adverts.Include(i => i.ImagePaths).SingleOrDefault(i => i.Id == id);

            var users = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>().Users.ToList();
            var user = users.FirstOrDefault(x => x.Id == advert.UserID);
            ViewBag.Advertiser = user.Name;
                if (advert == null)
            {
                return HttpNotFound();
            }
            return View(advert);
        }

        // GET: Adverts/Create
        [Authorize(Roles = "Admin,User")]
        public ActionResult Create()

        {
            return View();
        }

        // POST: Adverts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Description,UserID,Images")] Advert advert)
        {

            
            advert.UserID = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                List<ImagePath> imagePaths = new List<ImagePath>();
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    var file = Request.Files[i];

                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        ImagePath imagePath = new ImagePath()
                        {
                            FileName = fileName,
                            Extension = Path.GetExtension(fileName),
                            Id = Guid.NewGuid()
                        };
                        imagePaths.Add(imagePath);

                        var path = Path.Combine(Server.MapPath("~/App_Data/Upload/"), imagePath.Id + imagePath.Extension);
                        file.SaveAs(path);
                    }
                }

                advert.ImagePaths = imagePaths;
                db.Adverts.Add(advert);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(advert);
        }

        // GET: Adverts/Edit/5
        [Authorize(Roles = "Admin,User")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advert advert = db.Adverts.Include(s => s.ImagePaths).SingleOrDefault(x => x.Id == id);
            if (advert == null)
            {
                return HttpNotFound();
            }
            return View(advert);
        }

        // POST: Adverts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Advert advert)
        {
            if (ModelState.IsValid) { 

                List<ImagePath> imagePaths;
                if (advert.ImagePaths != null)
                    imagePaths = advert.ImagePaths.ToList();
                else
                    imagePaths = new List<ImagePath>();

                for (int i = 0; i < Request.Files.Count; i++)
                {
                    var file = Request.Files[i];

                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        ImagePath fileDetail = new ImagePath()
                        {
                            FileName = fileName,
                            Extension = Path.GetExtension(fileName),
                            Id = Guid.NewGuid(),
                            AdvertID = advert.Id.ToString()
                        };
                        var path = Path.Combine(Server.MapPath("~/App_Data/Upload/"), fileDetail.Id + fileDetail.Extension);
                        file.SaveAs(path);
                        //db.ImagePaths.Add(fileDetail);
                        imagePaths.Add(fileDetail);
                        db.Entry(fileDetail).State = EntityState.Added;
                    }
                }

                advert.ImagePaths = imagePaths;

                db.Entry(advert).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(advert);
        }

        // GET: Adverts/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advert advert = db.Adverts.Find(id);
            if (advert == null)
            {
                return HttpNotFound();
            }
            return View(advert);
        }

        // POST: Adverts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Advert advert = db.Adverts.Find(id);

            foreach (var item in advert.ImagePaths)
            {
                String path = Path.Combine(Server.MapPath("~/App_Data/Upload/"), item.Id + item.Extension);
                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                }
            }
            db.Adverts.Remove(advert);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult DeleteFile(string id)
        {
            if (String.IsNullOrEmpty(id))
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { Result = "Error" });
            }
            try
            {
                Guid guid = new Guid(id);
                ImagePath fileDetail = db.ImagePaths.Find(guid);
                if (fileDetail == null)
                {
                    Response.StatusCode = (int)HttpStatusCode.NotFound;
                    return Json(new { Result = "Error" });
                }
                
                db.ImagePaths.Remove(fileDetail);
                db.SaveChanges();
                
                var path = Path.Combine(Server.MapPath("~/App_Data/Upload/"), fileDetail.Id + fileDetail.Extension);
                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                }
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        public FileResult Download(String p, String d)
        {
            return File(Path.Combine(Server.MapPath("~/App_Data/Upload/"), p), System.Net.Mime.MediaTypeNames.Application.Octet, d);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SerwisOgloszeniowy/Views/Adverts/Create.cshtml
@model SerwisOgloszeniowy.Models.Advert

@{
    ViewBag.Title = "Utwórz";
}



@using (Html.BeginForm("Create", "Adverts", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Advert</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description,10,50, new { htmlAttributes = new { @class = "form-control", @cols = 120, @rows = 12} })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div class="form-group">
            @Html.Label("Zdjęcia", new { @class = "control-label col-md-2" })
            <div class="editor-field">
                <input type="file" name="file" multiple="multiple" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Utwórz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Powrót", "Index")
</div>

SerwisOgloszeniowy/Views/Adverts/Delete.cshtml
@model SerwisOgloszeniowy.Models.Advert


@{
    ViewBag.Title = "Usuń";
}




    <h3>Czy jesteś pewien że chcesz usunąć to ogłoszenie?</h3>
    <div>
        <h4>@Html.DisplayFor(model => model.Title)</h4>
        <hr />
        <dl class="dl-horizontal">

    
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
    

    

    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>

SerwisOgloszeniowy/Views/Adverts/Details.cshtml
@model SerwisOgloszeniowy.Models.Advert


@{
    ViewBag.Title =this.Model.Title;
}


<style>
    .details {
        margin-top: 50px;
    }
    .carousel-control{
        width: 50px;
            
    }
    .carousel-img {
        margin-left: auto;
        margin-right: auto;
    }
    #myCarousel{
        width: 60%;
        margin-left: auto;
        margin-right: auto;
    }

</style>

    <div class="details">
        <h4>@Html.DisplayFor(model => model.Title)</h4>
        <hr />


            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                @for (int i = 0; i < Model.ImagePaths.Count; i++)
                {
                   if (i == 0)
                    {
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    }
                    else
                    {

                        <li data-target="#myCarousel" data-slide-to="@i"></li>
                    }
                }
                </ol>
            <div class="carousel-inner" role="listbox"> 
                @foreach (var item in Model.ImagePaths)
                {
                    if (item.Id == Model.ImagePaths.First().Id)
                    {
                        <div class="item active">
                            <img class="carousel-img" src="/Adverts/Download/?p=@(item.Id + item.Extension)&d=@item.FileName">
                        </div>
                    }
                    else
                    {
                        <div class="item">
                            <img class="carousel-img" src="/Adverts/Download/?p=@(item.Id + item.Extension)&d=@item.FileName">
                        </div>
                    }


                }

                </div>

                <!-- Left and right controls -->
                <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        <dl>
            <dt>
                Wystawiający:
            </dt>

            <dd>
                @ViewBag.Advertiser
            </dd>

            <dt>
                Opis:
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
   
    

            
        </dl>
    </div>
    <p>
        @if ((User.IsInRole("User") && ViewBag.CurrentID == Model.UserID) || User.IsInRole("Admin"))
        {
            @Html.ActionLink("Edytuj", "Edit", new { id = Model.Id })
            
        }
            
        @Html.ActionLink("Powrót", "Index")
    </p>

SerwisOgloszeniowy/Views/Adverts/Edit.cshtml
@model SerwisOgloszeniowy.Models.Advert


@{
    ViewBag.Title = "Edycja";
}

    @using (Html.BeginForm("Edit", "Adverts", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Advert</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Description, 10, 50, new { htmlAttributes = new { @class = "form-control", @cols = 120, @rows = 12 } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="editor-label">
                    <label>Zdjęcia:</label>
                </div>
                <div class="col-md-10 editor-field">
                    <input type="file" name="file" multiple="multiple" />

                    <ul class="attachment">
                        @foreach (var item in Model.ImagePaths)
                        {
                            <li>
                                <a class="title" href="/Adverts/Download/?p=@(item.Id + item.Extension)&d=@item.FileName">@item.FileName</a>
                                <a href="javascript:void(0);" data-id="@item.Id" class="deleteItem">X</a>
                            </li>
                        }
                    </ul>
                </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
@section Scripts {
<script>

    $('.deleteItem').click(function (e) {
        e.preventDefault();
        var $ctrl = $(this);
        if (confirm('Czy na penwo chcesz usunąć ten plik?')) {
            $.ajax({
                url: '@Url.Action("DeleteFile")',
                type: 'POST',
                data: { id: $(this).data('id') }
            }).done(function (data) {
                if (data.Result == "OK") {
                    $ctrl.closest('li').remove();
                }
                else if (data.Result.Message) {
                    alert(data.Result.Message);
                }
            }).fail(function () {
                alert("There is something wrong. Please try again.");
            })

        }
    });


</script>


}

SerwisOgloszeniowy/Views/Adverts/Index.cshtml
@model PagedList.IPagedList<SerwisOgloszeniowy.Models.Advert>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Create";
}
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<div class="adverts">

    <p>
        @if (User.IsInRole("User") || User.IsInRole("Admin"))
        {
            @Html.ActionLink("Create New", "Create")
        }
    </p>

    @using (Html.BeginForm())
    {
        <div>Tytuł: </div>
        <div>@Html.TextBox("TitleSearch")</div>
        <div>Opis: </div>
        <div>@Html.TextBox("DescriptionSearch")</div>
        <input type="submit" value="Szukaj" />
    }

    <table class="table">
        <tr>
            <th>
                @Html.ActionLink("Id", "Index", new { sortOrder = ViewBag.IdSortParm })
            </th>
            <th>
                @Html.ActionLink("Tytuł", "Index", new { sortOrder = ViewBag.TitleSortParm })
            </th>

            <th>
                Zdjęcie
            </th>

            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.ActionLink(Html.DisplayFor(modelItem => item.Title).ToHtmlString(), "Details", new { id = item.Id })

                </td>


                @if (item.ImagePaths.Count > 0)
                {
                    <td>
                        <img class="thumb" src="/Adverts/Download/?p=@(item.ImagePaths.First().Id + item.ImagePaths.First().Extension)&d=@item.ImagePaths.First().FileName">
                    </td>
                }
                else
                {
                    <td>
                        <img class="thumb" src="/Adverts/Download/?p=no-image.png">
                    </td>
                }
                <td>
                    @if (User.IsInRole("User"))
                    {
                        if (ViewBag.CurrentID == item.UserID)
                        {
                            @Html.ActionLink("Edytuj", "Edit", new { id = item.Id })
                        }
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        @Html.ActionLink("Edytuj", "Edit", new { id = item.Id })  
                        <br/>
                        @Html.ActionLink("Usuń", "Delete", new { id = item.Id })
                     }
                    
                </td>
            </tr>
        }

    </table>
    <br /> Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
</div>
    <style>
        .adverts p {
            margin-top: 20px;
        }
        .adverts .thumb{
            max-height: 50px;
        }
        .adverts form {
            margin-top: 25px;

        }
        .adverts form div  {
            float: left;
            margin-right: 15px;
            margin-bottom: 15px;
        }
    </style>